// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDTr2DUpjEa6N8Slc3qGhB4eH5K_V6zs10',
    appId: '1:58179398698:web:3e9eaf11031788fca06753',
    messagingSenderId: '58179398698',
    projectId: 'login-7116d',
    authDomain: 'login-7116d.firebaseapp.com',
    storageBucket: 'login-7116d.firebasestorage.app',
    measurementId: 'G-PWN8094KR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlT0a26_oNvP5ACRUfe6_p1pPqWPH9nuM',
    appId: '1:58179398698:android:1f08862813d62c94a06753',
    messagingSenderId: '58179398698',
    projectId: 'login-7116d',
    storageBucket: 'login-7116d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVptt1YrDZIT97vkRvcqeFzCNCfmP29-o',
    appId: '1:58179398698:ios:5defa72d7a119906a06753',
    messagingSenderId: '58179398698',
    projectId: 'login-7116d',
    storageBucket: 'login-7116d.firebasestorage.app',
    iosBundleId: 'com.example.firebase2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDTr2DUpjEa6N8Slc3qGhB4eH5K_V6zs10',
    appId: '1:58179398698:web:00a3726bfdcfe7d2a06753',
    messagingSenderId: '58179398698',
    projectId: 'login-7116d',
    authDomain: 'login-7116d.firebaseapp.com',
    storageBucket: 'login-7116d.firebasestorage.app',
    measurementId: 'G-EYBQRY0SQF',
  );
}
